spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
  context-path: /sell

#注意：上面原先是
#server:
#  port: 8999
#  servlet:
#    context-path: /sell/

swagger:
  enable: true
  title: 用户子系统
  description: 用户子系统
  version: 1.0.0
  base-package: com.imooc.controller

wechat:
  mpAppId: wx5d13e80e550bebc0
  mpAppSecret: 24eeb372ee246d990359917524baf09b
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

# keyPath：是退款所需要的证书

#wechat:
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
